# Generated by Django 5.2.7 on 2025-10-24 03:46

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=156)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Case Study Category',
                'verbose_name_plural': 'Case Study Categories',
            },
        ),
        migrations.CreateModel(
            name='CaseStudyTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=156)),
            ],
            options={
                'verbose_name': 'Case Study Tag',
                'verbose_name_plural': 'Case Study Tags',
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('h1', models.CharField(max_length=156)),
                ('slug', models.CharField(blank=True, max_length=1256, null=True, unique=True)),
                ('page_name', models.CharField(blank=True, max_length=1256, null=True)),
                ('client_name', models.CharField(blank=True, max_length=256, null=True)),
                ('client_industry', models.CharField(blank=True, max_length=256, null=True)),
                ('project_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('project_date', models.DateField(blank=True, null=True)),
                ('keyword', models.CharField(max_length=156)),
                ('description', models.CharField(max_length=900)),
                ('title', models.CharField(max_length=156)),
                ('breadcrumb', models.CharField(max_length=156)),
                ('canonical', models.CharField(default='https://yoursite.com/case-studies/', max_length=900)),
                ('og_type', models.CharField(default='article', max_length=156)),
                ('og_card', models.CharField(default='summary_large_image', max_length=156)),
                ('og_site', models.CharField(blank=True, max_length=156, null=True)),
                ('og_title', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=100, null=True)),
                ('og_description', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(upload_to='case_study/SEO')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='case_study/banner')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='case_study/thumbnail')),
                ('challenge', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Describe the challenge/problem', null=True)),
                ('solution', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Describe the solution provided', null=True)),
                ('results', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Describe the results achieved', null=True)),
                ('testimonial', models.TextField(blank=True, help_text='Client testimonial', null=True)),
                ('testimonial_author', models.CharField(blank=True, max_length=256, null=True)),
                ('testimonial_position', models.CharField(blank=True, max_length=256, null=True)),
                ('metric_1_label', models.CharField(blank=True, help_text="e.g., 'Increase in Sales'", max_length=100, null=True)),
                ('metric_1_value', models.CharField(blank=True, help_text="e.g., '150%'", max_length=50, null=True)),
                ('metric_2_label', models.CharField(blank=True, max_length=100, null=True)),
                ('metric_2_value', models.CharField(blank=True, max_length=50, null=True)),
                ('metric_3_label', models.CharField(blank=True, max_length=100, null=True)),
                ('metric_3_value', models.CharField(blank=True, max_length=50, null=True)),
                ('metric_4_label', models.CharField(blank=True, max_length=100, null=True)),
                ('metric_4_value', models.CharField(blank=True, max_length=50, null=True)),
                ('technologies_used', models.TextField(blank=True, help_text='Comma separated technologies/services', null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('published', models.DateField()),
                ('updated', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False, help_text='Mark as featured case study')),
                ('edits', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('schema', models.TextField(blank=True, null=True)),
                ('gallery_image_1', models.ImageField(blank=True, null=True, upload_to='case_study/gallery')),
                ('gallery_image_2', models.ImageField(blank=True, null=True, upload_to='case_study/gallery')),
                ('gallery_image_3', models.ImageField(blank=True, null=True, upload_to='case_study/gallery')),
                ('gallery_image_4', models.ImageField(blank=True, null=True, upload_to='case_study/gallery')),
                ('category', models.ManyToManyField(to='IT.casestudycategory')),
                ('tag', models.ManyToManyField(to='IT.casestudytags')),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
                'ordering': ['-published'],
            },
        ),
    ]
